// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: notificaciones.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificadorService_ProcesarNotificacion_FullMethodName = "/notificaciones.NotificadorService/ProcesarNotificacion"
)

// NotificadorServiceClient is the client API for NotificadorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificadorServiceClient interface {
	// Java llama a esto para pasar la orden con sus marcas de tiempo
	ProcesarNotificacion(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*NotificacionResponse, error)
}

type notificadorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificadorServiceClient(cc grpc.ClientConnInterface) NotificadorServiceClient {
	return &notificadorServiceClient{cc}
}

func (c *notificadorServiceClient) ProcesarNotificacion(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*NotificacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificacionResponse)
	err := c.cc.Invoke(ctx, NotificadorService_ProcesarNotificacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificadorServiceServer is the server API for NotificadorService service.
// All implementations must embed UnimplementedNotificadorServiceServer
// for forward compatibility.
type NotificadorServiceServer interface {
	// Java llama a esto para pasar la orden con sus marcas de tiempo
	ProcesarNotificacion(context.Context, *MatchRequest) (*NotificacionResponse, error)
	mustEmbedUnimplementedNotificadorServiceServer()
}

// UnimplementedNotificadorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificadorServiceServer struct{}

func (UnimplementedNotificadorServiceServer) ProcesarNotificacion(context.Context, *MatchRequest) (*NotificacionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcesarNotificacion not implemented")
}
func (UnimplementedNotificadorServiceServer) mustEmbedUnimplementedNotificadorServiceServer() {}
func (UnimplementedNotificadorServiceServer) testEmbeddedByValue()                            {}

// UnsafeNotificadorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificadorServiceServer will
// result in compilation errors.
type UnsafeNotificadorServiceServer interface {
	mustEmbedUnimplementedNotificadorServiceServer()
}

func RegisterNotificadorServiceServer(s grpc.ServiceRegistrar, srv NotificadorServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotificadorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificadorService_ServiceDesc, srv)
}

func _NotificadorService_ProcesarNotificacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificadorServiceServer).ProcesarNotificacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificadorService_ProcesarNotificacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificadorServiceServer).ProcesarNotificacion(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificadorService_ServiceDesc is the grpc.ServiceDesc for NotificadorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificadorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notificaciones.NotificadorService",
	HandlerType: (*NotificadorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcesarNotificacion",
			Handler:    _NotificadorService_ProcesarNotificacion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notificaciones.proto",
}
